project:
  type: website
  output-dir: docs

website:
  favicon: "img/logo/logo_LB_black.png"
  title: "LA BERGERIE"
  navbar:
    left:
      - href: index.qmd
        text: "ğŸ La Bergerie"
      - href: pres.qmd
        text: "ğŸ“ˆ PrÃ©sentation gÃ©nÃ©rale"
      - href: photo_gallery.qmd
        text: "ğŸ“¸ Photographies"
    tools:
      - icon: "bi bi-person-arms-up"
        menu:
          - text: "ğŸ‘© Alanis"
            href: "Alanis.qmd"
          - text: "ğŸ‘¨ Alexandre"
            href: "Alexandre.qmd"
          - text: "ğŸ‘¨ Amory"
            href: "Amory.qmd"
          - text: "ğŸ‘¨ Benjamin"
            href: "Benjamin.qmd"
          - text: "ğŸ‘¨ Benoit"
            href: "Benoit.qmd"
          - text: "ğŸ‘© Cassandre"
            href: "Cassandre.qmd"
          - text: "ğŸ‘© Chelsea"
            href: "Chelsea.qmd"
          - text: "ğŸ‘© Coralie"
            href: "Coralie.qmd"
          - text: "ğŸ‘© Flavie"
            href: "Flavie.qmd"
          - text: "ğŸ‘¨ Killian"
            href: "Killian.qmd"
          - text: "ğŸ‘© Patricia"
            href: "Patricia.qmd"
          - text: "ğŸ‘© ValÃ©rie"
            href: "ValÃ©rie.qmd"
      - icon: "bi bi-person-raised-hand"
        menu:
          - text: "ğŸ‘¨ Christophe"
            href: "Christophe.qmd"
          - text: "ğŸ‘¨ FrÃ©dÃ©ric"
            href: "FrÃ©dÃ©ric.qmd"
          - text: "ğŸ‘¨ Gilles"
            href: "Gilles.qmd"
          - text: "ğŸ‘© Lydie"
            href: "Lydie.qmd"
          - text: "ğŸ‘© Sandra"
            href: "Sandra.qmd"
      - icon: "bi bi-bug-fill"
        menu:
          - text: "Mia"
            href: "Mia.qmd"
          - text: "Hajime"
            href: "Hajime.qmd"
          - text: "Teddy"
            href: "Teddy.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual